spring:
  datasource:
    username: root
    password: y973593589
    url: jdbc:mysql://192.168.1.13:3306/mall?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
    host: 192.168.1.13
    port: 6379
  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
logging:
  path: D:/mirai/IDEAworkSpace/mmall/my-log/
ftp:
  server:
    ip: 192.168.1.13
    port: 21
    remotePath: image  #FTP根目录下的目录，如果为空就表示在FTP根目录下
  username: ftpuser
  password: y973593589
server:
  port: 8888